export const SET_FOCUS_REQUEST = "set_focus_request"
export const REMOVE_FOCUS_REQUEST = "remove_focus_request"
export const GET_ALL_FILTERS = "get_all_filters"
export const SET_FILTER = "set_filter"
export const REMOVE_FILTER = "remove_filter"
export const CLEAR_ALL_FILTERS = "clear_filters"